# Generated by Django 4.2.1 on 2023-06-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmailverify', '0002_alter_profile_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gmailotp',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobileotp',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
